# public/admin/config.yml
backend:
  name: github
  repo: DEIN_GITHUB_USER/ROKKO_Web   # <- GitHub Username + Repo-Name eintragen
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - file: "src/data/site.json"
        label: "Settings"
        name: "settings"
        format: "json"
        fields:
          - { label: "Kontakt E-Mail", name: "contactEmail", widget: "string", default: "" }
          - { label: "Hintergrund", name: "bg", widget: "string", default: "#262626" }
          - { label: "Akzent 1", name: "accent1", widget: "string", default: "#483D03" }
          - { label: "Textfarbe", name: "text", widget: "string", default: "#F5F3BB" }
          - { label: "Akzent 2", name: "accent2", widget: "string", default: "#96897B" }

  - name: "artists"
    label: "Artists"
    file: "src/data/artists.json"
    format: "json"
    fields:
      - label: "Artists"
        name: "items"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Bio", name: "bio", widget: "text", required: false }
          - label: "Releases"
            name: "releases"
            widget: "list"
            fields:
              - { label: "Release Name", name: "name", widget: "string" }
              - { label: "Cover", name: "cover", widget: "image" }
              - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
              - { label: "Picture", name: "picture", widget: "image", required: false }
              - label: "Tracks"
                name: "tracks"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "File", name: "file", widget: "file" }
