backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - file: "src/data/site.json"
        label: "Settings"
        name: "settings"
        format: "json"
        fields:
          - { label: "Kontakt E-Mail", name: "contactEmail", widget: "string", default: "" }
          - { label: "Hintergrund", name: "bg", widget: "string", default: "#262626" }
          - { label: "Akzent 1", name: "accent1", widget: "string", default: "#483D03" }
          - { label: "Textfarbe", name: "text", widget: "string", default: "#F5F3BB" }
          - { label: "Akzent 2", name: "accent2", widget: "string", default: "#96897B" }
